#!/usr/bin/env python3

import re, sys

def _num2chr(m):
    return '{:c}'.format(int(m.group(1)))

lines = []
for line in sys.stdin:
    a = line.split()
    lines.append((-float(a[0]), re.sub('_([0-9]+)_', _num2chr, a[-1]).lower(), line))
lines.sort()
for line in lines:
    sys.stdout.write(line[-1])
