#!/usr/bin/env python3

import sys

lines = []
for line in sys.stdin:
    a = line.split(None, 4)
    #lines.append((-float(a[0]), -float(a[1]), -float(a[2]), a[4], line))
    lines.append((-float(a[0]), a[-1], line))
lines.sort()
for line in lines:
    sys.stdout.write(line[-1])
