#!/usr/bin/env python3
"""
--documentation--
"""

__author__ = "Peter Kleiweg"
__version__ = "0.1"
__date__ = "2010/10/03"

#| imports

import sys

#| main

fp = open(sys.argv[1], 'rt', encoding='iso-8859-1')
lines = fp.readlines()
fp.close()

values = []
NAs = []
state = 0
for lineno in range(len(lines)):
    line = lines[lineno].strip()
    if not line or line[0] == '#':
        continue
    if state == 0:
        n = int(line)
        i = 0
        state = 1
    elif state == 1:
        i += 1
        if i == n:
            state = 2
    else:
        if line == 'NA':
            NAs.append(lineno)
        else:
            values.append(float(line))

values.sort()
newval = '{:g}\n'.format(values[int(len(values) * .75)])
for i in NAs:
    lines[i] = newval

fp = open(sys.argv[2], 'wt', encoding='iso-8859-1')
for line in lines:
    fp.write(line)
fp.close()
