#!/usr/bin/env python3

import sys

def unquote(s):
    s = s.strip()
    if s[0] == '"' and s[-1] == '"':
        return s[1:-1].replace('\\\\', '\n').replace('\\', '').replace('\n', '\\').strip()
    else:
        return s

labels = []

fp = open(sys.argv[1], 'rt', encoding='iso-8859-1')
for line in fp:
    try:
        a, b = line.split(None, 1)
        int(a)
    except:
        pass
    else:
        b = unquote(b)
        labels.append(b)
fp.close()

fp = open(sys.argv[2], 'wt', encoding='iso-8859-1')
for label in labels:
    fp.write(': {0}\n- {0}\n'.format(label))
fp.close()
             
