#!/usr/bin/env python3
"""
--documentation--
"""

__author__ = "Peter Kleiweg"
__version__ = "0.1"
__date__ = "2010/10/03"

#| imports

import sys

#| main

state = 0
NAs = 0
fp = open(sys.argv[1], 'rt', encoding='iso-8859-1')
for line in fp:
    line = line.strip()
    if not line or line[0] == '#':
        continue
    if state == 0:
        n = int(line)
        i = 0
        state = 1
    elif state == 1:
        i += 1
        if i == n:
            state = 2
    else:
        if line == 'NA':
            NAs += 1
fp.close()

if NAs:
    sys.stderr.write('There are {} NAs\n'.format(NAs))
    sys.exit(1)
