#!/usr/bin/env python3
"""

Usage:

cluster -wm ../diff/diff.txt | clgroup -i -n 2 > grp2
cluster -wm ../diff/diff.txt | clgroup -i -n 3 > grp3
grp2dif grp2 ../diff/diff.txt grp2.dif
grp2dif grp3 ../diff/diff.txt grp3.dif
R < norm.R


"""

__author__ = "Peter Kleiweg"
__version__ = "0.1"
__date__ = "2010/05/06"

#| imports

import cgitb; cgitb.enable(format="text")

import os, sys

#| globals

#| functions

def unquote(s):
    s = s.strip()
    if s[0] == '"' and s[-1] == '"':
        return s[1:-1].replace('\\\\', '\n').replace('\\', '').replace('\n', '\\').strip()
    else:
        return s


#| main

grpfile = sys.argv[1]
diffile = sys.argv[2]
outfile = sys.argv[3]

idx = {}
lbls = []

fp = open(diffile, 'rt', encoding='iso-8859-1')
for line in fp:
    line = line.strip()
    if not line or line[0] == '#':
        continue
    n = int(line)
    break
for i in range(n):
    for line in fp:
        line = line.strip()
        if not line or line[0] == '#':
            continue
        idx[line] = i
        lbls.append(line)
        break
fp.close()

grp = [0] * n

fp = open(grpfile, 'rt', encoding='iso-8859-1')
for line in fp:
    line = line.strip()
    if not line or line[0] == '#':
        continue
    c, s = line.split(None, 1)
    s = unquote(s)
    grp[idx[s]] = 1 << (int(c) - 1)
fp.close()


fp = open(outfile, 'wt',  encoding='iso-8859-1')
fp.write('{}\n'.format(n))
for lbl in lbls:
    fp.write(lbl + '\n')
for i in range(n):
    for j in range(i):
        fp.write('{}\n'.format(grp[i] | grp[j]))
fp.close()
