#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
--documentation--
"""

__author__ = "Peter Kleiweg"
__version__ = "0.1"
__date__ = "2010/10/09"

#| imports

import cgitb; cgitb.enable(format="text")

import re, sys

import u.html

#| globals

#| main

if len(sys.argv) > 1:
    prefix = mapname = sys.argv[1]
else:
    mapname = 'map1'
    prefix = 'c'


truelabels = {}
fp1 = open('../data/labels.txt', 'rt', encoding='iso-8859-1')
fp2 = open('../data/truelabels.txt', 'rt', encoding='utf-8')
for line in fp1:
    lbl = line.split(None, 1)[1].strip()
    truelabels[lbl] = fp2.readline().strip()
fp2.close()
fp1.close()

items = []
fp = open('image.coo', 'rt', encoding='iso-8859-1')
for line in fp:
    line = line.strip()
    x, y, s = line.split(None, 2)
    s = u.html.escape(truelabels.get(s, s))
    items.append((x, y, s))
fp.close()

fp = open('image.html', 'wt', encoding='utf-8')
fp.write('<map name="{}">\n'.format(mapname))
for i in range(len(items)):
    fp.write('<area href="#" onmouseover="popUp(event,\'{2}{0}\')" onmouseout="stopTimer()" onclick="return false" shape="circle" coords="{1[0]},{1[1]},5">\n'.format(i, items[i], prefix))
fp.write('</map>\n')
for i in range(len(items)):
    fp.write('<div id="{2}{0}" class="tip" onMouseOut="popDown(event,\'{2}{0}\')">{1}</div>\n'.format(i, items[i][2], prefix))
fp.close()
