#!/usr/bin/env python3

import cgitb; cgitb.enable(format="text")

import os, time, shutil, stat, sys

limit = time.time() - 60 * 60 * 24 * 2

os.chdir(os.environ['DATADIR'])
for dirname in sorted(os.listdir('.')):
    t = dirname + '/TIMESTAMP'
    if os.access(t, os.F_OK):
        if dirname.startswith('demo') or dirname.startswith('.demo'):
            pass
        elif dirname.startswith('guest'):
            if os.stat(t)[stat.ST_MTIME] < limit:
                for filename in os.listdir(dirname):
                    if filename == 'tmp' or filename.startswith('project'):
                        sys.stdout.write('Removing guest data: {}/{}\n'.format(dirname, filename))
                        shutil.rmtree(dirname + '/' + filename)
