#!/usr/bin/env python3
"""
--documentation--
"""

#| imports

import re, sys

def unquote(s):
    s = s.strip()
    if not s:
        return ''
    if s[0] == '"' and s[-1] == '"':
        return s[1:-1].replace('\\\\', '\n').replace('\\', '').replace('\n', '\\').strip()
    else:
        return s

#| main

n = int(sys.argv[1])
if sys.version_info[0] > 2:
    fpin = open(sys.argv[2], 'r', encoding='iso-8859-1')
    fpout = open(sys.argv[3], 'w', encoding='iso-8859-1')
else:
    fpin = open(sys.argv[2], 'r')
    fpout = open(sys.argv[3], 'w')
for line in fpin:
    a, b = line.split(None, 1)
    b = unquote(b)
    if int(a) == n:
        if sys.version_info[0] > 2:
            fpout.write(': {0}\n- {0}\n'.format(b))
        else:
            fpout.write(': %s\n- %s\n' % (b, b))
fpout.close()
fpin.close()
